BaseURL = "https://erickhun.com/"
title = "Eric Khun"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "erickhun"
googleAnalytics = "UA-106516-7"

[params]
    author = "Eric Khun"
    info = "engineering @ <a href=\"https://buffer.com\">buffer</a> <br/> 🎨 <a href=\"https://project-memento.com\">project memento (NFT)</a>  🇹🇼  <a href=\"https://taiwangoldcard.com\">taiwangoldcard.com</a> 🌃  <a href=\"https://citymayor.co\">citymayor.co (NFT)</a> "
    description = "Eric Khun's essays - I write about Taiwan - Scalability - Infrastructure - Engineering"
    keywords = "blog, developer, personal, data"
    avatarurl = "img/eric.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Feel free to contact me <a href=\"https://twitter.com/eric_khun\">@eric_khun</a>"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    # custom_css = ["css/custom.css"]


# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/eric_khun"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 2
    url = "https://www.instagram.com/juiced69"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/erickhun"
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/erickhun"
[[params.social]]
    name = "Talks"
    icon = "fab fa-slideshare fa-2x"
    weight = 1
    url = "https://speakerdeck.com/erickhun"


# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/"

[[menu.main]]
    name = "Talks"
    weight = 2
    url  = "https://speakerdeck.com/erickhun/"


[[menu.main]]
    name = "About me"
    weight = 3
    url = "/about"

[taxonomies]
    tag = "tags"
    tutorial = "tutorials"
    category = "categories"

[markup.goldmark.renderer]
    unsafe = true
