BaseURL = "http://erickhun.com/"
theme = "hugo-geo"
relativeURLs = false
languageCode = "en-us"
title = "Eric Khun"
disqusShortname = "Eric"
paginate = 5

[taxonomies]
    tag = "tags"
    tutorial = "tutorials"

[params]
    # Render the rotating globe in the sidebar
    showglobe = true

    # Google Analytics
    analytics = "UA-106516-7"

    # Social buttons for sidebar
    github = "https://github.com/erickhun"
    twitter = "https://twitter.com/eric_khun"
    linkedin = "https://www.linkedin.com/in/erickhun"
    #email = ""

    # Sidebar profile picture
    profilepic = "img/eric.jpg"

    # Title/subtitle for the sidebar
    title = "Eric KHUN"
    subtitle = "Software Engineer"

    # Nav links below the profile picture
    [[params.navlinks]]
    name = "About"
    url = "about/"

    [[params.navlinks]]
    name = "Blog"
    url = "posts/"

    [[params.navlinks]]
    name = "Tutorials"
    url = "tutorial/"
