baseurl = "http://erickhun.github.io/"
title = "My New Hugo Site"
languageCode = "en-us"
theme = "startbootstrap-clean-blog"
paginate = 10
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Eric Khun"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Your site description"
  Author = "Eric Khun"
  email = "hello [ at ] erickhun.com"
  Ganalytics = "XX-00000000-0"